name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: install dependencies
        run: npm install

      - name: run audit test
        run: npm audit

  unit-test:
    runs-on: ubuntu-latest
    needs: security-test
    steps:
      - name: Checkout of the Repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: npm start &

      - name: Run tests
        run: npm run test:unit

  e2e-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install playwright browsers
        run: npx playwright install

      - name: Run app
        run: npm start &

      - name: Run e2e tests
        run: npm run test:ui

  deploy-render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: e2e-test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{secrets.MY_RENDER_SERVICE_ID}}
          api-key: ${{secrets.MY_RENDER_API_KEY}}
